@Portify_API_HostAddress = https://localhost:7001

# Portify API Endpoints
# GitHub Login Endpoint
@state = abc123xyz
@code = variable value
GET {{Portify_API_HostAddress}}/auth/github-login?state={{state}}
# GitHub Callback Endpoint
# GitHub Login Endpoint with Code
# This endpoint is used to handle the callback from GitHub after user authentication

